language: php
sudo: required
dist: xenial

addons:
  sonarcloud:
    organization: morgonus

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4

env:
  global:
    - LINT_COMMAND="composer lint"
    - TEST_COMMAND="composer test"
    - DOCKER_VERSION=19.03.8

matrix:
  fast_finish: true
  include:
    - php: 7.3
      sudo: required
      services:
        - docker
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true SONAR=true TEST_COMMAND="composer test-ci"

before_install:
  - sudo apt-cache madison docker-engine
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add –
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - sudo apt-get install unzip wget nodejs
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction
  - docker pull registry:latest
  - docker run -p 5000:5000 -d registry

script:
  - $TEST_COMMAND
  - $LINT_COMMAND
  - php vendor/bin/phpunit
  - $SONAR_COMMAND


after_success:
  - if [[ "$COVERAGE" = true ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; fi
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --access-token="0e196f4fccde66a08ad662bbcd892293ed9d1ec538fc02e387c2d2ef2c6dd54a" --format=php-clover coverage.clover; fi
  - if [[ "$SONAR" = true ]]; then php vendor/bin/phpunit && sonar-scanner; fi

after_script:
  - sudo cat /var/log/upstart/docker.log