language: php
sudo: required
dist: xenial

addons:
  sonarcloud:
    organization: morgonus
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - LINT_COMMAND="composer lint"
    - TEST_COMMAND="composer test"
    - DOCKER_VERSION=19.03.11~ce-0~ubuntu


before_install:
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  - sudo apt-get install unzip wget nodejs
  - travis_retry composer self-update
  - sudo apt-get update
  - sudo apt-cache madison docker-ce
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-ce
  - sudo docker ps
  - sudo docker version

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction
  - docker pull registry:latest
  - docker run -p 5000:5000 -d registry

script:
  - $TEST_COMMAND
  - $LINT_COMMAND
  - php vendor/bin/phpunit
  - $SONAR_COMMAND


after_success:
  - if [[ "$COVERAGE" = true ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; fi
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --access-token="0e196f4fccde66a08ad662bbcd892293ed9d1ec538fc02e387c2d2ef2c6dd54a" --format=php-clover coverage.clover; fi
  - if [[ "$SONAR" = true ]]; then php vendor/bin/phpunit && sonar-scanner; fi

after_script:
  - sudo cat /var/log/upstart/docker.log