language: php
sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

php: 7.2

env:
  global:
    - TEST_COMMAND="composer test"
    - DOCKER_VERSION=19.03.8

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 7.1
      sudo: required
      services:
          - docker
      env: DOCKER_API_VERSION=1.25 DOCKER_VERSION=17.03.2~ce-0~ubuntu-trusty COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci"
    - php: 7.1
      env: DOCKER_API_VERSION=1.36 DOCKER_VERSION=18.02.0~ce-0~ubuntu TEST_COMMAND="composer lint"
    - php: 7.2
      sudo: required
      services:
          - docker
      env: DOCKER_API_VERSION=1.36 DOCKER_VERSION=18.02.0~ce-0~ubuntu

before_install:
  - sudo apt-get update
  - sudo apt-cache madison docker-ce
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-ce=${DOCKER_VERSION}
  - travis_retry composer self-update

install:
  - travis_retry composer install
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - travis_retry composer require docker-php/docker-php-api:4.${DOCKER_API_VERSION}.*

script:
  - $TEST_COMMAND

after_success:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi

after_script:
  - sudo cat /var/log/upstart/docker.log
