php54:
  image: jolicode/php54
  command: sh -c 'cd /app && COMPOSER_MEMORY_LIMIT=-1 composer update && vendor/bin/phpunit'
  user: root
  volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - COMPOSER_MEMORY_LIMIT=-1
php55:
  image: jolicode/php55
  command: sh -c 'cd /app && COMPOSER_MEMORY_LIMIT=-1 composer update && vendor/bin/phpunit'
  user: root
  volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - COMPOSER_MEMORY_LIMIT=-1
php56:
  image: phundament/php-one:5.6-fpm
  command: sh -c 'COMPOSER_MEMORY_LIMIT=-1 composer update && vendor/bin/phpunit'
  volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - COMPOSER_MEMORY_LIMIT=-1
php70:
  image: phundament/php-one:7.0-fpm
  command: sh -c 'COMPOSER_MEMORY_LIMIT=-1 composer update && vendor/bin/phpunit'
  volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - COMPOSER_MEMORY_LIMIT=-1
